 function Work_Window
% create work window and controls

% handle of figure
global hFig1;
% handles of contrles 'pushbutton'
global hBut1 hBut2 hBut3 hBut4 ;
% handles of contrles 'text'
global hTxtys1 hTxtys1T hTxtys2 hTxtys2T hTxtys3 hTxtys3T;
global hTxtys4 hTxtys4T;

% flag for stop and move of wave packet
global mov;
mov = 1;
% create figure 
 hFig1=figure( ...
    'Name','Korneev V.I.,  Wave Packet Tunneling from Square Barrier', ...
    'NumberTitle','off');

% create control - pushbutton <Start>
hBut1 = uicontrol(hFig1,'Style','pushbutton',...
    'String','Start',...
    'Units','normalized', ...
    'Position',[0.91 0.85 0.08 0.05],...
    'Callback','Move_Packet');

% create control - pushbutton <Stop>
hBut2 = uicontrol(hFig1,'Style','pushbutton',...
    'String','Stop',...
    'Units','normalized', ...
    'Position',[0.91 0.75 0.08 0.05],...
    'Enable','off', ...
    'Callback','Stop_Move(-1)');

% create control - pushbutton <Move>
hBut3 = uicontrol(hFig1,'Style','pushbutton',...
    'String','Move',...
    'Units','normalized', ...
    'Position',[0.91 0.65 0.08 0.05],...
    'Enable','off', ...
    'Callback','Stop_Move(1)');

% create control - pushbutton <Close>
hBut4 = uicontrol(hFig1,'Style','pushbutton',...
    'String','Close',...
    'Units','normalized', ...
    'Position',[0.91 0.55 0.08 0.05],...
    'Enable','off', ...
    'Callback','Stop_Move(2)');

% create control - text
hTxtys1T = uicontrol(hFig1,'Style','text',...
    'String','t (fs) = ',...
    'Units','normalized', ...
    'Position',[0.01 0.95 0.08 0.035],...
    'Visible','off',...    
    'BackgroundColor',[0.5 0.6 0.7]);

% create control - text
hTxtys1 = uicontrol(hFig1,'Style','text',...
    'String','0',...
    'Units','normalized', ...
    'Position',[0.1 0.95 0.12 0.035],...
    'Visible','off',...    
    'BackgroundColor',[0.8 0.7 0.7]);

% create control - text
hTxtys2T = uicontrol(hFig1,'Style','text',...
    'String','P1 = ',...
    'Units','normalized', ...
    'Position',[0.25 0.95 0.08 0.035],...
    'Visible','off',...    
    'BackgroundColor',[0.5 0.6 0.7]);

% create control - text
hTxtys2 = uicontrol(hFig1,'Style','text',...
    'String','0',...
    'Units','normalized', ...
    'Position',[0.34 0.95 0.12 0.035],...
    'Visible','off',...    
    'BackgroundColor',[0.8 0.7 0.7]);

% create control - text
hTxtys3T = uicontrol(hFig1,'Style','text',...
    'String','P2 = ',...
    'Units','normalized', ...
    'Position',[0.49 0.95 0.08 0.035],...
    'Visible','off',...    
    'BackgroundColor',[0.5 0.6 0.7]);

% create control - text
hTxtys3 = uicontrol(hFig1,'Style','text',...
    'String','0',...
    'Units','normalized', ...
    'Position',[0.58 0.95 0.12 0.035],...
    'Visible','off',...    
    'BackgroundColor',[0.8 0.7 0.7]);

% create control - text
hTxtys4T = uicontrol(hFig1,'Style','text',...
    'String','P3 = ',...
    'Units','normalized', ...
    'Position',[0.73 0.95 0.08 0.035],...
    'Visible','off',...    
    'BackgroundColor',[0.5 0.6 0.7]);

% create control - text
hTxtys4 = uicontrol(hFig1,'Style','text',...
    'String','0',...
    'Units','normalized', ...
    'Position',[0.82 0.95 0.12 0.035],...
    'Visible','off',...    
    'BackgroundColor',[0.8 0.7 0.7]);

